<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="actionGuardModel"
    nsURI="http://actionGuardModel" nsPrefix="actionGuardModel">
  <eClassifiers xsi:type="ecore:EClass" name="AnElementList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anElement" upperBound="-1"
        eType="#//AnElement" containment="true" eOpposite="#//AnElement/anElementList"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anElementList" lowerBound="1"
        eType="#//AnElementList" eOpposite="#//AnElementList/anElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
