<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="function"
    nsURI="http://function" nsPrefix="function">
  <eClassifiers xsi:type="ecore:EClass" name="FunctionList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" upperBound="-1"
        eType="#//Function" containment="true" eOpposite="#//Function/functionList"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function">
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionList" lowerBound="1"
        eType="#//FunctionList" eOpposite="#//FunctionList/function"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnedType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameter" upperBound="-1"
        eType="ecore:EDataType ../../model/model/dscDiagramModel.ecore#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
